export const config = {
	project: {
		name: "Start School",
		slogan: "Right Time Right Now",
		description:
			"At Start Schools, we empower individuals with the skills and knowledge they need to thrive in the dynamic world of cloud technologies. Our comprehensive bootcamps equip you with the expertise to master essential cloud platforms like AWS, Azure, and Google Cloud Platform, enabling you to confidently navigate the ever-evolving landscape of cloud computing.",
		version: "1.0.0",
	},
	contact: {
		phone1: "+49 (176) 489-4335",
		phone2: "+49 (176) 489-4336",
		email: "info@schools.com",
		address: "1035 Park Ave, Berlin, NY 10128, DE",
		website: "https://schools.com",
		mapURL: "https://maps.app.goo.gl/wcxBJNRAFvM8eEMG9",
		mapEmbedURL:"https://www.google.com/maps/embed?pb=!1m26!1m12!1m3!1d9711.647594554848!2d13.376856829070196!3d52.51693345109935!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!4m11!3e3!4m5!1s0x47a84e373f035901%3A0x42120465b5e3b70!2sBerlin!3m2!1d52.520006599999995!2d13.404954!4m3!3m2!1d52.5087495!2d13.3770364!5e0!3m2!1sen!2sde!4v1717934613388!5m2!1sen!2sde",
		socialMedia: {
			twitter: "https://twitter.com",
			facebook: "https://facebook.com",
			instagram: "https://instagram.com",
			linkedin: "https://linkedin.com",
			youtube: "https://youtube.com",
		},
	},
	api: {
		baseUrl: "https://mycampusmates.com/app",
	},

	educationTerms: [
		{ label: "Fall", value: "FALL_SEMESTER" },
		{ label: "Spring", value: "SPRING_SEMESTER" },
	],
	genders: [
		{ label: "Female", value: "FEMALE" },
		{ label: "Male", value: "MALE" },
	],
	days: [
		{ value: "MONDAY", label: "Monday" },
		{ value: "TUESDAY", label: "Tuesday" },
		{ value: "WEDNESDAY", label: "Wednesday" },
		{ value: "THURSDAY", label: "Thursday" },
		{ value: "FRIDAY", label: "Friday" },
		{ value: "SATURDAY", label: "Saturday" },
		{ value: "SUNDAY", label: "Sunday" },
	],
	userRightsOnRoutes: [
		{urlRegex: /\/dashboard$/, roles:["ADMIN", "MANAGER", "ASSISTANTMANAGER", "TEACHER", "STUDENT"]},
		{urlRegex: /\/dashboard\/admin$/, roles:["ADMIN"]},
		{urlRegex: /\/dashboard\/admin\/new$/, roles:["ADMIN"]},
		{urlRegex: /\/dashboard\/manager$/, roles:["ADMIN"]},
		{urlRegex: /\/dashboard\/manager\/new$/, roles:["ADMIN"]},
		{urlRegex: /\/dashboard\/manager\/[0-9]+$/, roles:["ADMIN"]},
		{urlRegex: /\/dashboard\/assistant-manager$/, roles:["ADMIN", "MANAGER"]},
		{urlRegex: /\/dashboard\/assistant-manager\/new$/, roles:["ADMIN", "MANAGER"]},
		{urlRegex: /\/dashboard\/assistant-manager\/[0-9]+$/, roles:["ADMIN", "MANAGER"]},
		{urlRegex: /\/dashboard\/teacher$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/teacher\/new$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/teacher\/[0-9]+$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/lesson$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/lesson\/new$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/education-term$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/education-term\/new$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/program$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/program\/new$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/student$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/student\/new$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/student\/[0-9]+$/, roles:["ADMIN", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/student-info$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/student-info\/new$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/student-info\/[0-9]+$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/meet$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/meet\/new$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/meet\/[0-9]+$/, roles:["TEACHER"]},
		{urlRegex: /\/dashboard\/contact-message$/, roles:["ADMIN", "MANAGER", "ASSISTANTMANAGER"]},
		{urlRegex: /\/dashboard\/choose-lesson$/, roles:["STUDENT"]},
		{urlRegex: /\/dashboard\/grades-meets$/, roles:["STUDENT"]},
	]
		
};
